// css
import "./globals.css";

// metadata
export const metadata = {
  title: "Wind Breaker | Live Forecast ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
